import { beforeEach, describe, expect, it } from 'vitest';

import type { BatchEepResult } from '@/api/types';
import {
  batchPanelState,
  canCollapse,
  collapseKey,
  failedCountOf,
  isCollapsed,
  liveFailedIds,
  readCollapsed,
  writeCollapsed,
} from './batchPanelModel';

const base = { totalCount: 24, unanalyzedCount: 9, running: false, hasSummary: false, failedCount: 0 };

describe('batchPanelState', () => {
  it('state 1: pending items, no run yet this visit', () => {
    expect(batchPanelState(base)).toBe('pending');
  });

  it('state 2: running wins over everything, even when nothing is left', () => {
    expect(batchPanelState({ ...base, running: true })).toBe('running');
    expect(batchPanelState({ ...base, running: true, unanalyzedCount: 0 })).toBe('running');
  });

  it('state 3: a run finished and there are failures or pending items', () => {
    expect(batchPanelState({ ...base, hasSummary: true, failedCount: 2 })).toBe('attention');
    expect(batchPanelState({ ...base, hasSummary: true, unanalyzedCount: 3 })).toBe('attention');
  });

  it('state 4: nothing unanalyzed and no failure', () => {
    expect(batchPanelState({ ...base, unanalyzedCount: 0 })).toBe('done');
    expect(batchPanelState({ ...base, unanalyzedCount: 0, hasSummary: true })).toBe('done');
  });

  it('nothing unanalyzed but a failure still counted is not done', () => {
    expect(batchPanelState({ ...base, unanalyzedCount: 0, hasSummary: true, failedCount: 1 })).toBe(
      'attention',
    );
  });

  it('an empty book is not "all analyzed"', () => {
    expect(batchPanelState({ ...base, totalCount: 0, unanalyzedCount: 0 })).toBe('pending');
  });

  it('count rising again returns to state 1', () => {
    expect(batchPanelState({ ...base, unanalyzedCount: 0 })).toBe('done');
    expect(batchPanelState({ ...base, unanalyzedCount: 4 })).toBe('pending');
  });
});

describe('canCollapse / isCollapsed', () => {
  it('only states 1-3 collapse; the status row has no fold', () => {
    expect(canCollapse('pending')).toBe(true);
    expect(canCollapse('running')).toBe(true);
    expect(canCollapse('attention')).toBe(true);
    expect(canCollapse('done')).toBe(false);
    expect(isCollapsed('done', true)).toBe(false);
    expect(isCollapsed('running', true)).toBe(true);
    expect(isCollapsed('pending', false)).toBe(false);
  });
});

const summary = (over: Partial<BatchEepResult>): BatchEepResult => ({
  progress: 24,
  total: 24,
  failed: 2,
  skipped: 15,
  ...over,
});

describe('liveFailedIds / failedCountOf', () => {
  const failures = [
    { reason: 'x', event_id: 'e1', title: 'A' },
    { reason: 'y', event_id: 'e2', title: 'B' },
  ];

  it('keeps failures that are still unanalyzed', () => {
    const s = summary({ failures });
    expect(liveFailedIds(s, ['e1', 'e2', 'e3'], 'events')).toEqual(['e1', 'e2']);
    expect(failedCountOf(s, ['e1', 'e2'])).toBe(2);
  });

  it('drops a failure that was generated by hand afterwards', () => {
    const s = summary({ failures });
    const live = liveFailedIds(s, ['e2'], 'events');
    expect(live).toEqual(['e2']);
    expect(failedCountOf(s, live)).toBe(1);
  });

  it('uses entity_id for the characters page, event_id for events', () => {
    const s = summary({ failures: [{ reason: 'r', entity_id: 'c1', name: 'N' }] });
    expect(liveFailedIds(s, ['c1'], 'characters')).toEqual(['c1']);
    expect(liveFailedIds(s, ['c1'], 'events')).toEqual([]);
  });

  it('is empty without a summary or without failures', () => {
    expect(liveFailedIds(null, ['e1'], 'events')).toEqual([]);
    expect(failedCountOf(null, [])).toBe(0);
    expect(failedCountOf(summary({ failed: 0, failures: [] }), [])).toBe(0);
  });

  it('falls back to the tally when the old result carries no ids', () => {
    const s = summary({ failed: 3, failures: [{ reason: 'r', imagery_id: 'i' }] });
    expect(liveFailedIds(s, ['i'], 'events')).toEqual([]);
    expect(failedCountOf(s, [])).toBe(3);
    expect(failedCountOf(summary({ failed: 2 }), [])).toBe(2);
  });
});

describe('collapse override storage', () => {
  beforeEach(() => localStorage.clear());

  it('is keyed by book and page', () => {
    expect(collapseKey('b1', 'events')).toBe('storysphere:batch-panel:b1:events');
    expect(collapseKey('b1', 'characters')).toBe('storysphere:batch-panel:b1:characters');
  });

  it('a collapsed characters page does not touch the events page', () => {
    writeCollapsed(collapseKey('b1', 'characters'), true);
    expect(readCollapsed(collapseKey('b1', 'characters'))).toBe(true);
    expect(readCollapsed(collapseKey('b1', 'events'))).toBe(false);
    expect(readCollapsed(collapseKey('b2', 'characters'))).toBe(false);
  });

  it('expanding removes the override', () => {
    const k = collapseKey('b1', 'events');
    writeCollapsed(k, true);
    writeCollapsed(k, false);
    expect(localStorage.getItem(k)).toBeNull();
  });
});
