"""LLM-based named entity extraction (NER) using Gemini structured output.

For each chapter text chunk, the LLM returns a JSON list of entities
validated against a Pydantic schema.  Retries (up to 3) are performed on
parse failures (ADR-007).
"""

from __future__ import annotations

import json
import logging
from typing import Any

from pydantic import BaseModel, Field, ValidationError
from tenacity import retry, retry_if_exception_type, stop_after_attempt, wait_exponential

from domain.entities import Entity, EntityType

logger = logging.getLogger(__name__)


# ── Pydantic schema for LLM output ──────────────────────────────────────────


class _RawEntity(BaseModel):
    """Schema for a single entity as returned by the LLM."""

    name: str
    entity_type: str = "other"
    aliases: list[str] = Field(default_factory=list)
    description: str | None = None
    attributes: dict[str, Any] = Field(default_factory=dict)


class _EntityList(BaseModel):
    entities: list[_RawEntity] = Field(default_factory=list)


# ── Extractor ────────────────────────────────────────────────────────────────


_SYSTEM_PROMPT = """\
You are a literary NER system.  Extract all named entities from the provided
novel chapter text.

Return ONLY a JSON object with the key "entities" whose value is a list.
Each element must have:
  - "name"        (str)            The canonical name as it appears in the text.
  - "entity_type" (str)            One of: character, location, organization,
                                   object, concept, other.
  - "aliases"     (list[str])      Other names or titles for the same entity.
  - "description" (str | null)     A one-sentence description.
  - "attributes"  (dict)           Any notable attributes (age, gender, role…).

Do NOT include pronouns or generic nouns.  Only include specific named things.
"""


class EntityExtractor:
    """Extract entities from chapter text using a structured LLM call."""

    def __init__(self, llm=None) -> None:
        """
        Args:
            llm: A LangChain ``BaseChatModel``.  If None, the primary LLM is
                 resolved lazily from ``get_llm_client()``.
        """
        self._llm = llm

    def _get_llm(self):
        if self._llm is None:
            from core.llm_client import get_llm_client  # noqa: PLC0415

            self._llm = get_llm_client().get_primary(temperature=0.0)
        return self._llm

    async def extract(self, text: str, chapter_number: int) -> list[Entity]:
        """Extract entities from a chapter text string.

        Args:
            text: Chapter text (may be the concatenation of all paragraphs).
            chapter_number: Used to populate ``Entity.first_appearance_chapter``.

        Returns:
            List of ``Entity`` objects (IDs auto-generated by Pydantic).
        """
        if not text.strip():
            return []

        raw_list = await self._call_llm_with_retry(text)
        entities = self._parse(raw_list, chapter_number)
        logger.info(
            "EntityExtractor: chapter=%d  extracted=%d entities", chapter_number, len(entities)
        )
        return entities

    # ── LLM call (with retry) ────────────────────────────────────────────────

    @retry(
        retry=retry_if_exception_type((ValidationError, json.JSONDecodeError, ValueError)),
        stop=stop_after_attempt(3),
        wait=wait_exponential(multiplier=1, min=1, max=5),
        reraise=True,
    )
    async def _call_llm_with_retry(self, text: str) -> _EntityList:
        from langchain_core.messages import HumanMessage, SystemMessage  # noqa: PLC0415

        llm = self._get_llm()
        messages = [
            SystemMessage(content=_SYSTEM_PROMPT),
            HumanMessage(content=f"Chapter text:\n\n{text[:8000]}"),
        ]
        response = await llm.ainvoke(messages)
        content = response.content if hasattr(response, "content") else str(response)
        return _parse_json_response(content)

    # ── Parsing ──────────────────────────────────────────────────────────────

    @staticmethod
    def _parse(raw_list: _EntityList, chapter_number: int) -> list[Entity]:
        entities: list[Entity] = []
        for raw in raw_list.entities:
            try:
                etype = EntityType(raw.entity_type.lower())
            except ValueError:
                etype = EntityType.OTHER
            entities.append(
                Entity(
                    name=raw.name,
                    entity_type=etype,
                    aliases=raw.aliases,
                    description=raw.description,
                    attributes=raw.attributes,
                    first_appearance_chapter=chapter_number,
                )
            )
        return entities


# ── Shared JSON parser ───────────────────────────────────────────────────────


def _parse_json_response(content: str) -> _EntityList:
    """Extract JSON from LLM text (may be wrapped in markdown fences)."""
    content = content.strip()
    # Strip ```json ... ``` fences if present
    if content.startswith("```"):
        lines = content.splitlines()
        content = "\n".join(
            line for line in lines if not line.strip().startswith("```")
        ).strip()
    data = json.loads(content)
    return _EntityList.model_validate(data)
